name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages

      - name: Wait for deployment to finish
        run: sleep 30 # Espera 30 segundos (ajusta según tu necesidad)

      - name: Trigger page reload
        uses: softprops/action-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}